name: gnthibault remote observatory
observatory:
    module: ShedObservatory
    investigator: gnthibault
    latitude: 43.56 # Degrees
    longitude: 5.43 # Degrees
    elevation: 150.0 # Meters
    # UTC+1 CET Central European Time,
    # UTC +2  CEST Central European Summer Time
    utc_offset: 1 # Hours
    horizon: # Degrees
        0 : 30
        90 : 30
        180 : 30
        270 : 30
    twilight_horizon: -18 # Degrees
    timezone: Europe/Paris
    # Paris is in the Central European Time Zone ( CET ) is 1 hours ahead of
    # Greenwich Mean Time ( GMT+1 ).
    gmt_offset: 60 # Minutes
    scope_controller:
        module: DummyScopeController #IndiArduiScopeController
        port: /dev/ttyACM0
        controller_name: Arduino
        indi_driver_connect_delay_s: 5
        indi_camera_driver_name: Canon DSLR
        indi_mount_driver_name: Losmandy Gemini
        indi_webserver_host: 192.168.0.33
        indi_webserver_port: 8624
        indi_client :
            indi_host : localhost
            indi_port : 7624
    dome_controller:
        module : IndiRorController
        port : /dev/ttyACM1
        indi_client :
            indi_host : localhost
            indi_port : 7624
directories:
    base: /var/RemoteObservatory
    images: images
    webcam: webcams
    data: data
    resources: resources/
    targets: resources/targets
    mounts: resources/mounts
db: 
    name: /var/RemoteObservatory/DB
    type: file
ntp:
    ntpserver: time.google.com
scheduler:
    #module: DefaultScheduler
    module: SpectroScheduler
    #target_file: targets
    target_file: spectral_targets
spectroscope_controller:
    module: IndiSpectroController
calibration:
    #module: ImagingCalibration
    module: SpectralCalibration
    spectral_calib:
        nb: 11
        sec: 30
        gain: 1
        temperature:
    flat:
        nb: 21
        sec: 5
        gain: 1
        temperature:
    dark:
        dark_nb: 11
    controller:
        module: DummySpectroController
        controller_name: dummy
        #module: IndiSpectroController
        #controller_name: spox
mount:
    #module: IndiG11
    #mount_name: Losmandy Gemini
    module: IndiAbstractMount
    mount_name : Telescope Simulator
    indi_client :
        indi_host : localhost
        indi_port : 7624
pointing_camera:
    module: IndiAbstractCamera
    camera_name : Guide Simulator
    pointing_seconds: 10
    autofocus_seconds: 2
    autofocus_size : 500
    indi_client :
        indi_host : localhost
        indi_port : 7624
acquisition_camera:
    module: IndiAbstractCamera
    camera_name : CCD Simulator
    #module: IndiEos6DCamera
    #camera_name: Canon DSLR EOS 6D
    #camera_name: GPhoto CCD
    CCD_INFO :
        CCD_MAX_X : 5472
        CCD_MAX_Y : 3648
        CCD_PIXEL_SIZE : 6.5
        CCD_PIXEL_SIZE_X : 6.5
        CCD_PIXEL_SIZE_Y : 6.5
        CCD_BITSPERPIXEL : 14
    pointing_seconds: 30
    autofocus_seconds: 5
    autofocus_size : 500
    indi_client :
        indi_host : localhost
        indi_port : 7624
    focuser:
        module: IndiFocuser
        focuser_name : Focuser Simulator
        port : /dev/ttyUSB0
        focus_range :
            min : 30000
            max : 50000
        autofocus_step :
            fine : 250
            coarse : 2500
        autofocus_range :
            fine : 10000
            coarse : 20000
        indi_client :
            indi_host : localhost
            indi_port : 7624
#filterwheel:
nofilterwheel:
    module : IndiFilterWheel 
    filterwheel_name : Filter Simulator
    filter_list : 
        Luminance : 1
        Red : 2
        Green : 3
        Blue : 4
        H_Alpha : 5
        OIII : 6
        SII : 7
        LPR : 8
    indi_client :
        indi_host : localhost
        indi_port : 7624
guider:
    module : GuiderPHD2
    host : localhost
    port : 4400
    publish_port : 6510
    profile_id : 1
    #profile_id : 2
    exposure_time_sec : 2
    settle :
        pixels : 1.5
        time : 10
        timeout : 60
    dither :
        pixels : 3.0
        ra_only : False
weather_service :
    #module : IndiOpenWeatherMap
    #service_name: OpenWeatherMap
    module : IndiWeather
    service_name : Weather Simulator
    key_path : /var/RemoteObservatory/keys.json
    publish_port : 6510
    delay_sec : 60
    limits :
        MAX_WEATHER_WIND_SPEED_KPH : 25
        MAX_WEATHER_WIND_GUST_KPH : 30
        MAX_WEATHER_CLOUD_COVER : 5
    indi_client :
        indi_host : localhost
        indi_port : 7624
time_service :
    module : HostTimeService
messaging:
    # Must match ports in peas.yaml.
    cmd_port: 6500
    msg_port: 6510
#Enable to output POCS messages to social accounts
# social_accounts:
#     twitter:
#         consumer_key: [your_consumer_key]
#         consumer_secret: [your_consumer_secret]
#         access_token: [your_access_token]
#         access_token_secret: [your_access_token_secret]
#     slack:
#         webhook_url: [your_webhook_url]
#         output_timestamp: False
state_machine: simple_state_table
