name: gnthibault remote observatory
location:
    name: gnthibault remote observatory
    latitude: 46.204391 # Degrees
    longitude: 6.143158 # Degrees
    elevation: 600.0 # Meters
    # UTC+1 CET Central European Time,
    # UTC +2  CEST Central European Summer Time
    utc_offset: 1 # Hours
    horizon: 30 # Degrees
    twilight_horizon: -18 # Degrees
    timezone: Europe/Paris
    # Paris is in the Central European Time Zone ( CET ) is 1 hours ahead of
    # Greenwich Mean Time ( GMT+1 ).
    gmt_offset: 60 # Minutes
directories:
    base: /var/RemoteObservatory
    images: images
    webcam: webcams
    data: data
    resources: resources/
    targets: resources/targets
    mounts: resources/mounts
db: 
    name: /var/RemoteObservatory/DB
    type: file
mount:
    brand: simulator
    driver: indi
messaging:
    # Must match ports in peas.yaml.
    cmd_port: 6500
    msg_port: 6510
#Enable to output POCS messages to social accounts
# social_accounts:
#     twitter:
#         consumer_key: [your_consumer_key]
#         consumer_secret: [your_consumer_secret]
#         access_token: [your_access_token]
#         access_token_secret: [your_access_token_secret] 
#     slack:
#         webhook_url: [your_webhook_url]
#         output_timestamp: False

state_machine: simple_state_table
