name: Remote observatory
observatory:
    module: Observatory
    investigator: gnthibault
    latitude: 45.67 # Degrees
    longitude: 5.67 # Degrees
    elevation: 150.0 # Meters
    timezone: Europe/Paris #This is not mandatory, just speeds up startup
    # UTC+1 CET Central European Time,
    # UTC +2  CEST Central European Summer Time
    utc_offset: 1 # Hours
    horizon: # Degrees
        0 : 0
        90 : 0
        180 : 0
        270 : 0
    twilight_horizon: -18 # Degrees
    timezone: Europe/Paris
    # Paris is in the Central European Time Zone ( CET ) is 1 hours ahead of
    # Greenwich Mean Time ( GMT+1 ).
    gmt_offset: 60 # Minutes
#    webcam:
#        rtsp_url: rtsp://user:password@192.168.0.16
    scope_controller:
        config_arduino:
            device_name: Arduino
            device_port: /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AB0L9VL1-if00-port0
            connection_type: CONNECTION_SERIAL
            baud_rate: 57600
            polling_ms: 1000
            indi_client:
                indi_host: localhost
                indi_port: 7624
        config_upbv2:
            device_name: Pegasus UPB
            device_port: /dev/serial/by-id/usb-Pegasus_Astro_UPBv2_revD_UPB25S4VWV-if00-port0
            connection_type: CONNECTION_SERIAL
            baud_rate: 9600
            polling_ms: 1000
            dustcap_travel_delay_s: 10
            adjustable_voltage_value: 5
            power_labels:
                POWER_LABEL_1: MAIN_TELESCOPE_DUSTCAP_CONTROL
                POWER_LABEL_2: SPOX_AND_DUSTCAP_POWER
                POWER_LABEL_3: MAIN_CAMERA_POWER
                POWER_LABEL_4: MOUNT_POWER
            always_on_power_identifiers:
                MAIN_TELESCOPE_DUSTCAP_CONTROL: True
                SPOX_AND_DUSTCAP_POWER: True
                MAIN_CAMERA_POWER: False
                MOUNT_POWER: False
            usb_labels:
                USB_LABEL_1: FIELD_CAMERA
                USB_LABEL_2: PRIMARY_CAMERA
                USB_LABEL_3: SPECTRO_CONTROL_BOX
                USB_LABEL_4: ARDUINO_CONTROL_BOX
                USB_LABEL_5: WIFI_ROUTER
                USB_LABEL_6: GUIDE_CAMERA
            always_on_usb_identifiers:
                FIELD_CAMERA: False
                PRIMARY_CAMERA: False
                SPECTRO_CONTROL_BOX: False
                ARDUINO_CONTROL_BOX: False
                WIFI_ROUTER: True,
                GUIDE_CAMERA: False
            dew_labels:
                DEW_LABEL_1: PRIMARY_FAN
                DEW_LABEL_2: SECONDARY_DEW_HEATER
                DEW_LABEL_3: FINDER_DEW_HEATER
            auto_dew_identifiers:
                PRIMARY_FAN: False
                SECONDARY_DEW_HEATER: True
                FINDER_DEW_HEATER: True
            auto_dew_aggressivity: 150 # Number between 50 and 250
            indi_client:
                indi_host: localhost
                indi_port: 7625
        indi_driver_connect_delay_s: 10
        indi_resetable_instruments_driver_name_list:
            driver_1: ZWO CCD
            driver_2: Altair
            driver_3: Shelyak SPOX
            driver_4: PlayerOne CCD
            driver_5: Arduino telescope controller
        indi_mount_driver_name: Losmandy Gemini
        indi_webserver_host: localhost
        indi_webserver_port: 8624
    dome_controller:
        module : IndiDomeController
        dome_movement_timeout_s: 300
        dome_name: Dome Simulator
        indi_client :
            indi_host : localhost
            indi_port : 7625
directories:
    base: /var/RemoteObservatory
    images: images
    webcam: webcams
    data: data
    resources: resources/
    targets: resources/targets
    mounts: resources/mounts
db: 
    name: /var/RemoteObservatory/DB
    type: file
ntp:
    ntpserver: time.google.com
scheduler:
    module: DefaultScheduler
    # module: SpectroScheduler
    target_file: targets.yaml
    #target_file: spectral_targets.yaml
spectroscope_controller:
    module: IndiSpectroController
calibration:
    module: ImagingCalibration
    #module: SpectralCalibration
    spectral_calib:
        nb: 11
        sec: 30
        gain: 1
        temperature:
    flat:
        nb: 1
        sec: 5
        gain: 1
        temperature:
    dark:
        dark_nb: 1
    controller:
        module: DummySpectroController
        controller_name: dummy
        #module: IndiSpectroController
        #controller_name: spox
mount:
    module: IndiG11
    mount_name: Losmandy Gemini
    equatorial_eod: J2000 # JNOW
    indi_client :
        indi_host : localhost
        indi_port : 7625
cameras:
    -
        module: IndiASICamera
        camera_name : ZWO CCD ASI290MM Mini
        do_acquisition: false
        SCOPE_INFO: # 200/800 newtonian
            FOCAL_LENGTH: 800
            APERTURE: 200
        do_guiding: true
        do_pointing: true
        pointing_seconds: 5
        do_adjust_pointing: true
        adjust_center_x: 580
        adjust_center_y: 400
        adjust_roi_search_size: 50
        adjust_pointing_seconds: 5
        do_autofocus: false
        autofocus_seconds: 4
        autofocus_roi_size : 750
        autofocus_merit_function: half_flux_radius
#        focuser:
#            module: IndiFocuser
#            focuser_name: Focuser Simulator
#            port: /dev/ttyUSB0
#            focus_range:
#                min: 32500
#                max: 40000
#            autofocus_step:
#                fine: 750
#                coarse: 2500
#            autofocus_range:
#                fine: 10000
#                coarse: 30000
#            indi_client:
#                indi_host: localhost
#                indi_port: 7625
        indi_client :
            indi_host : localhost
            indi_port : 7625
            #use_unique_client: True
    -
        module: IndiAbstractCamera
        camera_name : PlayerOne CCD Ares-M PRO
        do_acquisition: true
    #    CCD_INFO :
    #        CCD_MAX_X : 5496
    #        CCD_MAX_Y : 3672
    #        CCD_PIXEL_SIZE : 2.4
    #        CCD_PIXEL_SIZE_X : 2.4
    #        CCD_PIXEL_SIZE_Y : 2.4
    #        CCD_BITSPERPIXEL : 12
        SCOPE_INFO: # 200/800 newtonian
            FOCAL_LENGTH: 800
            APERTURE: 200
        do_guiding: false
        do_pointing: false
        pointing_seconds: 5
        do_adjust_pointing: true
        adjust_center_x: 400
        adjust_center_y: 400
        adjust_roi_search_size: 50
        adjust_pointing_seconds: 5
        do_autofocus: true
        autofocus_seconds: 5
        autofocus_roi_size : 750
        autofocus_merit_function : half_flux_radius #vollath_F4
        #focuser:
        #    module: IndiFocuser
        #    focuser_name: Focuser Simulator
        #    port: /dev/ttyUSB0
        #    focus_range:
        #        min: 32500
        #        max: 40000
        #    autofocus_step:
        #        fine: 750
        #        coarse: 2500
        #    autofocus_range:
        #        fine: 10000
        #        coarse: 30000
        #    indi_client:
        #        indi_host: localhost
        #        indi_port: 7625
        #do_filter_wheel: false
        #filter_wheel:
        #    module: IndiFilterWheel
        #    filterwheel_name: Filter Simulator
        #    filter_list:
        #        Luminance: 1
        #        Red: 2
        #        Green: 3
        #        Blue: 4
        #        H_Alpha: 5
        #        OIII: 6
        #        SII: 7
        #        LPR: 8
        #    indi_client:
        #        indi_host: localhost
        #        indi_port: 7625
        indi_client :
            indi_host : localhost
            indi_port : 7625
pointer:
    module: IterativeSync #DifferentialPointer #IterativeSync
    gen_hips: False
    timeout_seconds: 450
    max_iterations: 5
    max_pointing_error_seconds: 3
offset_pointer:
    module: StarOffsetPointer #StarOffsetPointer #NoOffsetPointer
    timeout_seconds: 300
    max_identification_error_seconds: 1
    sync_mount_upon_solve: False
    use_guider_adjust: False
    on_star_identification_failure: trust_astrometry # get_brightest or trust_astrometry
guider:
    module : GuiderPHD2
    host : 127.0.0.1
    port : 4400
    do_calibration : False
    profile_name : backyard
    exposure_time_sec : 4
    settle :
        pixels : 1.5
        time : 10
        timeout : 60
    dither :
        pixels : 0.0
        ra_only : False
weather_service :
    #module : IndiOpenWeatherMap
    #service_name: OpenWeatherMap
    module : IndiWeather
    service_name : Weather Simulator
    key_path : /var/RemoteObservatory/keys.json
    delay_sec : 60
    observatory:
        latitude: 43.56 # Degrees
        longitude: 5.43 # Degrees
        elevation: 150.0 # Meters
    limits :
        MAX_WEATHER_WIND_SPEED_KPH : 25
        MAX_WEATHER_WIND_GUST_KPH : 30
        MAX_WEATHER_CLOUD_COVER : 5
    indi_client :
        indi_host : localhost
        indi_port : 7625
vizualization_service:
        module: SceneVizualization
        delay_sky_update_s: 1
        delay_moving_objects_s: 0.05
        gps_coord:
            latitude: 45.67
            longitude: 5.67
time_service :
    module : HostTimeService
messaging_publisher:
    module: PanMessagingMQTT #PanMessagingZMQ, PanMessagingMQTT
    mqtt_host: localhost
    mqtt_port: 1883
    com_mode: publisher
    msg_port: 6510
messaging_subscriber:
    module: PanMessagingMQTT #PanMessagingZMQ, PanMessagingMQTT
    mqtt_host: localhost
    mqtt_port: 1883
    com_mode: subscriber
    cmd_port: 6500
paws_subscriber:
    module: PanMessagingMQTT #PanMessagingZMQ, PanMessagingMQTT
    mqtt_host: localhost
    mqtt_port: 1883
    com_mode: subscriber
    cmd_port: 6511
paws_publisher:
    module: PanMessagingMQTT #PanMessagingZMQ, PanMessagingMQTT
    mqtt_host: localhost
    mqtt_port: 1883
    com_mode: publisher
    msg_port: 6500
#independant_services:
#    -
#        module: NasaGCNService
#        delay_sec: 60
## If not provided, sourced from env NASA_GCN_CLIENT_ID and NASA_GCN_CLIENT_SECRET
##        client_info:
##            client_id:
##            client_secret:
#        messaging_publisher:
#            module: PanMessagingMQTT
#            mqtt_host: localhost
#            mqtt_port: 1883
#            com_mode: publisher

#Enable to output POCS messages to social accounts
# social_accounts:
#     twitter:
#         consumer_key: [your_consumer_key]
#         consumer_secret: [your_consumer_secret]
#         access_token: [your_access_token]
#         access_token_secret: [your_access_token_secret]
state_machine: simple_state_table.yaml
