#~ directories:
    #~ base: /var/RemoteObservatory
    #~ images: images
    #~ webcam: webcams
    #~ data: data
    #~ resources: resources/
    #~ targets: resources/targets
    #~ mounts: resources/mounts
#~ db: 
    #~ name: /var/RemoteObservatory/DB
    #~ type: file
#~ ntp:
    #~ ntpserver: time.google.com
#~ scheduler:
    #~ #module: DefaultScheduler
    #~ module: SpectroScheduler
    #~ #target_file: targets.yaml
    #~ target_file: spectral_targets.yaml
#~ spectroscope_controller:
    #~ module: IndiSpectroController
#~ calibration:
    #~ #module: ImagingCalibration
    #~ module: SpectralCalibration
    #~ spectral_calib:
        #~ nb: 2
        #~ sec: 5
        #~ gain: 150
        #~ offset: 30
        #~ temperature: 15
    #~ flat:
        #~ nb: 2
        #~ sec: 5
        #~ gain: 150
        #~ offset: 30
        #~ temperature: 15
    #~ dark:
        #~ dark_nb: 2
    #~ controller:
        #~ module: DummySpectroController
        #~ device_name: dummy
        #~ #module: IndiSpectroController
        #~ #device_name: spox
mount:
    module: Indi10Micron
    name : 10micron-GM1000
    equatorial_eod: J2000 # JNOW
    indi_client :
        indi_host : 192.168.144.32
        indi_port : 7624

science_camera:
    module: IndiASICamera
    name : ZWO CCD ASI183MM Pro # CCD Simulator
    indi_client :
        indi_host : 192.168.144.32
        indi_port : 7624

guiding_camera:
    module: IndiASICameraNonCool
    name : ZWO CCD ASI174MM Mini
    indi_client :
        indi_host : 192.168.144.32
        indi_port : 7624

focuser:
    module: IndiFocuser
    # focuser_name: Focuser Simulator
    name: FocusLynx_F1
    #~ port: /dev/serial/by-id/usb-Optec__Inc._Optec_USB_Serial_Cable_OP5AORA9-if00-port0 # /dev/ttyUSB0
    focus_range:
        min: 10200
        max: 11400
    autofocus_step:
        fine: 300
        coarse: 300
    autofocus_range:
        fine: 2000
        coarse: 2000
    indi_client:
        indi_host: 192.168.144.32 # localhost
        indi_port: 7624
        
filter_wheel:
    module: IndiFilterWheel
    name: Filter Simulator
    filter_list:
        Luminance: 1
        Red: 2
        Green: 3
        Blue: 4
        H_Alpha: 5
        OIII: 6
        SII: 7
        LPR: 8
    indi_client:
        indi_host: localhost
        indi_port: 7624

#~ pointer:
    #~ module: DifferentialPointer #DifferentialPointer #IterativeSync
    #~ gen_hips: False
    #~ timeout_seconds: 450
    #~ max_iterations: 5
    #~ max_pointing_error_seconds: 2
#~ offset_pointer:
    #~ module: StarOffsetPointer #StarOffsetPointer #NoOffsetPointer #InvisibleObjectOffsetPointer
    #~ timeout_seconds: 300
    #~ max_identification_error_seconds: 1
    #~ sync_mount_upon_solve: False
    #~ use_guider_adjust: True
    #~ on_star_identification_failure: trust_astrometry # get_brightest or trust_astrometry
    #~ max_iterations: 5
    #~ max_pointing_error_seconds: 2
#~ guider:
    #~ module : GuiderPHD2
    #~ host : localhost
    #~ host : 192.168.144.32
    #~ port : 4400
    #~ #profile_id : 1 # For IRL setup
    #~ do_calibration : False
    #~ profile_name : St-Pancrasse
    #~ exposure_time_sec : 0.5
    #~ settle :
        #~ pixels : 3
        #~ time : 10
        #~ timeout : 360
    #~ dither :
        #~ pixels : 0.0
        #~ ra_only : False
#~ weather_service :
    #~ #module : IndiOpenWeatherMap
    #~ #service_name: OpenWeatherMap
    #~ module : IndiWeather
    #~ service_name : Weather Simulator
    #~ key_path : /var/RemoteObservatory/keys.json
    #~ delay_sec : 60
    #~ observatory:
        #~ latitude: 43.56 # Degrees
        #~ longitude: 5.43 # Degrees
        #~ elevation: 150.0 # Meters
    #~ limits :
        #~ MAX_WEATHER_WIND_SPEED_KPH : 25
        #~ MAX_WEATHER_WIND_GUST_KPH : 30
        #~ MAX_WEATHER_CLOUD_COVER : 5
    #~ indi_client :
        #~ indi_host : 192.168.144.32
        #~ indi_port : 7624
#~ vizualization_service:
        #~ module: SceneVizualization
        #~ delay_sky_update_s: 1
        #~ delay_moving_objects_s: 0.05
        #~ show_stars: False
        #~ gps_coord:
            #~ latitude: 45.67
            #~ longitude: 5.67
#~ time_service :
    #~ module : HostTimeService
#~ messaging_publisher:
    #~ module: PanMessagingMQTT #PanMessagingZMQ, PanMessagingMQTT
    #~ mqtt_host: localhost
    #~ mqtt_port: 1883
    #~ com_mode: publisher
    #~ msg_port: 6510
#~ messaging_subscriber:
    #~ module: PanMessagingMQTT #PanMessagingZMQ, PanMessagingMQTT
    #~ mqtt_host: localhost
    #~ mqtt_port: 1883
    #~ com_mode: subscriber
    #~ cmd_port: 6500
#~ paws_subscriber:
    #~ module: PanMessagingMQTT #PanMessagingZMQ, PanMessagingMQTT
    #~ mqtt_host: localhost
    #~ mqtt_port: 1883
    #~ com_mode: subscriber
    #~ cmd_port: 6511
#~ paws_publisher:
    #~ module: PanMessagingMQTT #PanMessagingZMQ, PanMessagingMQTT
    #~ mqtt_host: localhost
    #~ mqtt_port: 1883
    #~ com_mode: publisher
    #~ msg_port: 6500

#independant_services:
#    -
#        module: NasaGCNService
#        delay_sec: 60
## If not provided, sourced from env NASA_GCN_CLIENT_ID and NASA_GCN_CLIENT_SECRET
##        client_info:
##            client_id:
##            client_secret:
#        messaging_publisher:
#            module: PanMessagingMQTT
#            mqtt_host: localhost
#            mqtt_port: 1883
#            com_mode: publisher

#Enable to output POCS messages to social accounts
# social_accounts:
#     twitter:
#         consumer_key: [your_consumer_key]
#         consumer_secret: [your_consumer_secret]
#         access_token: [your_access_token]
#         access_token_secret: [your_access_token_secret]
#~ state_machine: simple_state_table.yaml
