#~ directories:
    #~ base: /var/RemoteObservatory
    #~ images: images
    #~ webcam: webcams
    #~ data: data
    #~ resources: resources/
    #~ targets: resources/targets
    #~ mounts: resources/mounts

science_camera:
    module: IndiASICamera
    module_dir: IndiDevices.Camera
    camera_name : ZWO CCD ASI183MM Pro 
    class_name : IndiASICamera
    indi_client :
        indi_host : 192.168.144.32
        indi_port : 7624
    cooling : true
    cooling_capability : -20

mount:
    module: Indi10micronMount
    module_dir: IndiDevices.Mount
    mount_name : 10micron # 10micron-GM1000
    class_name : Indi10micronMount
    indi_client :
        indi_host : 192.168.144.32
        indi_port : 7624
    equatorial_eod: J2000 # JNOW

guiding_camera:
    module: IndiASICamera
    module_dir: IndiDevices.Camera
    camera_name : ZWO CCD ASI174MM Mini
    class_name : IndiASICamera
    indi_client :
        indi_host : 192.168.144.32
        indi_port : 7624
    cooling : false

ambiance_camera:
    module: IndiASICamera
    module_dir: IndiDevices.Camera
    camera_name : ZWO CCD ASI120MM-S
    class_name : IndiASICamera
    indi_client :
        indi_host : 192.168.144.32
        indi_port : 7624
    cooling : false

focuser:
    module: IndiFocuser
    module_dir: IndiDevices.Focuser
    focuser_name: FocusLynx F1
    class_name : IndiFocuser
    port: /dev/serial/by-id/usb-Optec__Inc._Optec_USB_Serial_Cable_OP5AORA9-if00-port0
    indi_client:
        indi_host: 192.168.144.32
        indi_port: 7624
    focus_range:
        min: 10200
        max: 11400
    autofocus_step:
        fine: 300
        coarse: 300
    autofocus_range:
        fine: 2000
        coarse: 2000
        
filter_wheel:
    module: IndiFilterWheel
    module_dir: IndiDevices.FilterWheel
    filterwheel_name: ASI EFW
    class_name : IndiFilterWheel
    indi_client: 
        indi_host: 192.168.144.32
        indi_port: 7624
    filter_list:
        Empty: 1
        530nm: 2
        630nm: 3
        None1: 4
        None2: 5

# UVEX:
#     module: UVEX
#     name: UVEX Spectroscope
#     indi_client:
#         indi_host: localhost
#         indi_port: 7624