#~ directories:
    #~ base: /var/RemoteObservatory
    #~ images: images
    #~ webcam: webcams
    #~ data: data
    #~ resources: resources/
    #~ targets: resources/targets
    #~ mounts: resources/mounts

science_camera:
    module: IndiASICamera
    module_dir: IndiDevices.Camera
    camera_name : ZWO CCD ASI183MM Pro
    indi_client :
        indi_host : 192.168.144.32
        indi_port : 7624
    cooling : true
    cooling_capability : -20

mount:
    module: IndiMount
    module_dir: IndiDevices.Mount
    mount_name : 10micron # 10micron-GM1000
    indi_client :
        indi_host : 192.168.144.32
        indi_port : 7624
    equatorial_eod: J2000 # JNOW

# guiding_camera:
#     module: IndiASICamera
#     camera_name : ZWO CCD ASI174MM Mini
#     cooling : false
#     indi_client :
#         indi_host : 192.168.144.32
#         indi_port : 7624

# ambiance_camera:
#     module: IndiASICamera
#     camera_name : ZWO CCD ASI120
#     cooling : false
#     indi_client :
#         indi_host : 192.168.144.32
#         indi_port : 7624

# focuser:
#     module: IndiFocuser
#     name: FocusLynx_F1
#     focus_range:
#         min: 10200
#         max: 11400
#     autofocus_step:
#         fine: 300
#         coarse: 300
#     autofocus_range:
#         fine: 2000
#         coarse: 2000
#     indi_client:
#         indi_host: 192.168.144.32 # localhost
#         indi_port: 7624
        
# filter_wheel:
#     module: IndiFilterWheel
#     name: Filter Simulator
#     filter_list:
#         Luminance: 1
#         Red: 2
#         Green: 3
#         Blue: 4
#         H_Alpha: 5
#         OIII: 6
#         SII: 7
#         LPR: 8
#     indi_client:
#         indi_host: localhost
#         indi_port: 7624

# UVEX:
#     module: UVEX
#     name: UVEX Spectroscope
#     indi_client:
#         indi_host: localhost
#         indi_port: 7624